name: Generate Snake Animation  # Custom blue snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: darkard2003
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#2E96F7&color_dots=#2DA44E,#39D353,#26A641,#006D32,#0E4429
            dist/github-contribution-grid-snake-dark.svg?color_snake=#2E96F7&color_dots=#0E4429,#006D32,#26A641,#39D353,#2DA44E&palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
